name: Deploy

on:
  push:
    branches:
      - docs
      - release/*
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set a Node.js version
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # pull code
      - name: Checkout code
        uses: actions/checkout@v3

      # using yarn to install deps
      - run: npm i -g yarn

      # build to static
      # - name: Build Example
        # run: yarn install && yarn build
        # working-directory: example

      # deploy to a branch
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          # The folder the action should deploy.
          folder: dist
          silent: true
          clean: true
          # This is the branch you wish to deploy to, for example, `gh-pages` or `docs`. Defaults to `gh-pages`.
          branch: gh-pages
          single-commit: true