name: Build and Deploy
on:
  push:
    branches:
      - docs
      - release/*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Set a Node.js version
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # using yarn to install deps
    - run: npm i -g yarn

    # pull code
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: yisibell/aidol
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: dist/